version: '3'

services:
  booking-1:
    build: .
    restart: always
    env_file:
      - .env
      - .env.booking1

  booking-2:
    build: .
    restart: always
    env_file:
      - .env
      - .env.booking2
